Use cloud-hosted collections only (#66)
* Query CMR for only cloud-hosted collections
* Add GitHub Actions workflow for linting/testing
* Describe use of vcrpy for testing.
* Do not mock MAAP when MAAP_PGT is set so vcrpy
  can properly record CMR query responses within the ADE
* Replace --live-stream (deprecated) with --no-capture-output
* Allow pre-commit.ci to run shellcheck
* Avoid calling conda in pre-commit (only check for outdated lock file)

Fixes #66, #24

diff --git a/bin/lock b/bin/lock
--- a/bin/lock
+++ b/bin/lock
@@ -2,6 +2,13 @@
 
 set -euo pipefail
 
+# In pre-commit.ci, conda is not available, so we cannot generate the lock file.
+# Instead, we must simply issue an error message and fail the build.
+if [[ "${PRE_COMMIT:-}" == "1" ]]; then
+    echo >&2 "The conda-lock.yml file is out of date.  Run 'make lock' to update it, then commit the changes."
+    exit 1
+fi
+
 bin=$(dirname "$(readlink -f "$0")")
 basedir=$(dirname "${bin}")
 
